# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_homeshow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='homeshow',
            table='axf_mainshow',
        ),
    ]
