# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_marketfoodtype_marketgoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketfoodtype',
            name='childtypenames',
            field=models.CharField(max_length=200),
        ),
    ]
