# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180727_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=100)),
                ('sex', models.BooleanField(default=1)),
                ('icon', models.ImageField(upload_to='icons')),
                ('isdelete', models.BooleanField(default=0)),
            ],
        ),
    ]
