# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cartmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartmodel',
            table='axf_cartmodel',
        ),
    ]
